/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as LegalTermsOfServiceRouteImport } from './routes/legal/terms-of-service'
import { Route as LegalPrivacyPolicyRouteImport } from './routes/legal/privacy-policy'
import { Route as AuthSelectOrgRouteImport } from './routes/_auth/select-org'
import { Route as AuthNewRouteImport } from './routes/_auth/new'
import { Route as AuthOrgRouteImport } from './routes/_auth/_org'
import { Route as AuthOrgDashboardIndexRouteImport } from './routes/_auth/_org/dashboard/index'
import { Route as AuthOrgDashboardLogsRouteImport } from './routes/_auth/_org/dashboard/logs'
import { Route as AuthOrgDashboardBillingRouteImport } from './routes/_auth/_org/dashboard/billing'
import { Route as ApiApiKeysWorkspaceIdProjectIdIndexRouteImport } from './routes/api/api-keys/$workspaceId.$projectId/index'
import { Route as AuthOrgProjectsProjectIdIndexRouteImport } from './routes/_auth/_org/projects/$projectId/index'
import { Route as ApiApiKeysWorkspaceIdProjectIdKeyIdRouteImport } from './routes/api/api-keys/$workspaceId.$projectId/$keyId'
import { Route as AuthOrgProjectsProjectIdReleasesRouteImport } from './routes/_auth/_org/projects/$projectId/releases'
import { Route as AuthOrgProjectsProjectIdLanguagesRouteImport } from './routes/_auth/_org/projects/$projectId/languages'
import { Route as AuthOrgProjectsProjectIdGlossaryRouteImport } from './routes/_auth/_org/projects/$projectId/glossary'
import { Route as AuthOrgProjectsProjectIdBuildsRouteImport } from './routes/_auth/_org/projects/$projectId/builds'
import { Route as AuthOrgProjectsProjectIdApiKeysRouteImport } from './routes/_auth/_org/projects/$projectId/api-keys'
import { Route as AuthOrgProjectsProjectIdScreenshotsIndexRouteImport } from './routes/_auth/_org/projects/$projectId/screenshots/index'
import { Route as AuthOrgProjectsProjectIdScreenshotsScreenshotIdIndexRouteImport } from './routes/_auth/_org/projects/$projectId/screenshots/$screenshotId/index'
import { Route as AuthOrgProjectsProjectIdNamespacesNamespaceIdEditorRouteImport } from './routes/_auth/_org/projects/$projectId/namespaces/$namespaceId/editor'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsOfServiceRoute = LegalTermsOfServiceRouteImport.update({
  id: '/legal/terms-of-service',
  path: '/legal/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyPolicyRoute = LegalPrivacyPolicyRouteImport.update({
  id: '/legal/privacy-policy',
  path: '/legal/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSelectOrgRoute = AuthSelectOrgRouteImport.update({
  id: '/select-org',
  path: '/select-org',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNewRoute = AuthNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrgRoute = AuthOrgRouteImport.update({
  id: '/_org',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrgDashboardIndexRoute = AuthOrgDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AuthOrgDashboardLogsRoute = AuthOrgDashboardLogsRouteImport.update({
  id: '/dashboard/logs',
  path: '/dashboard/logs',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AuthOrgDashboardBillingRoute = AuthOrgDashboardBillingRouteImport.update({
  id: '/dashboard/billing',
  path: '/dashboard/billing',
  getParentRoute: () => AuthOrgRoute,
} as any)
const ApiApiKeysWorkspaceIdProjectIdIndexRoute =
  ApiApiKeysWorkspaceIdProjectIdIndexRouteImport.update({
    id: '/api/api-keys/$workspaceId/$projectId/',
    path: '/api/api-keys/$workspaceId/$projectId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthOrgProjectsProjectIdIndexRoute =
  AuthOrgProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AuthOrgRoute,
  } as any)
const ApiApiKeysWorkspaceIdProjectIdKeyIdRoute =
  ApiApiKeysWorkspaceIdProjectIdKeyIdRouteImport.update({
    id: '/api/api-keys/$workspaceId/$projectId/$keyId',
    path: '/api/api-keys/$workspaceId/$projectId/$keyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthOrgProjectsProjectIdReleasesRoute =
  AuthOrgProjectsProjectIdReleasesRouteImport.update({
    id: '/projects/$projectId/releases',
    path: '/projects/$projectId/releases',
    getParentRoute: () => AuthOrgRoute,
  } as any)
const AuthOrgProjectsProjectIdLanguagesRoute =
  AuthOrgProjectsProjectIdLanguagesRouteImport.update({
    id: '/projects/$projectId/languages',
    path: '/projects/$projectId/languages',
    getParentRoute: () => AuthOrgRoute,
  } as any)
const AuthOrgProjectsProjectIdGlossaryRoute =
  AuthOrgProjectsProjectIdGlossaryRouteImport.update({
    id: '/projects/$projectId/glossary',
    path: '/projects/$projectId/glossary',
    getParentRoute: () => AuthOrgRoute,
  } as any)
const AuthOrgProjectsProjectIdBuildsRoute =
  AuthOrgProjectsProjectIdBuildsRouteImport.update({
    id: '/projects/$projectId/builds',
    path: '/projects/$projectId/builds',
    getParentRoute: () => AuthOrgRoute,
  } as any)
const AuthOrgProjectsProjectIdApiKeysRoute =
  AuthOrgProjectsProjectIdApiKeysRouteImport.update({
    id: '/projects/$projectId/api-keys',
    path: '/projects/$projectId/api-keys',
    getParentRoute: () => AuthOrgRoute,
  } as any)
const AuthOrgProjectsProjectIdScreenshotsIndexRoute =
  AuthOrgProjectsProjectIdScreenshotsIndexRouteImport.update({
    id: '/projects/$projectId/screenshots/',
    path: '/projects/$projectId/screenshots/',
    getParentRoute: () => AuthOrgRoute,
  } as any)
const AuthOrgProjectsProjectIdScreenshotsScreenshotIdIndexRoute =
  AuthOrgProjectsProjectIdScreenshotsScreenshotIdIndexRouteImport.update({
    id: '/projects/$projectId/screenshots/$screenshotId/',
    path: '/projects/$projectId/screenshots/$screenshotId/',
    getParentRoute: () => AuthOrgRoute,
  } as any)
const AuthOrgProjectsProjectIdNamespacesNamespaceIdEditorRoute =
  AuthOrgProjectsProjectIdNamespacesNamespaceIdEditorRouteImport.update({
    id: '/projects/$projectId/namespaces/$namespaceId/editor',
    path: '/projects/$projectId/namespaces/$namespaceId/editor',
    getParentRoute: () => AuthOrgRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/new': typeof AuthNewRoute
  '/select-org': typeof AuthSelectOrgRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard/billing': typeof AuthOrgDashboardBillingRoute
  '/dashboard/logs': typeof AuthOrgDashboardLogsRoute
  '/dashboard': typeof AuthOrgDashboardIndexRoute
  '/projects/$projectId/api-keys': typeof AuthOrgProjectsProjectIdApiKeysRoute
  '/projects/$projectId/builds': typeof AuthOrgProjectsProjectIdBuildsRoute
  '/projects/$projectId/glossary': typeof AuthOrgProjectsProjectIdGlossaryRoute
  '/projects/$projectId/languages': typeof AuthOrgProjectsProjectIdLanguagesRoute
  '/projects/$projectId/releases': typeof AuthOrgProjectsProjectIdReleasesRoute
  '/api/api-keys/$workspaceId/$projectId/$keyId': typeof ApiApiKeysWorkspaceIdProjectIdKeyIdRoute
  '/projects/$projectId': typeof AuthOrgProjectsProjectIdIndexRoute
  '/api/api-keys/$workspaceId/$projectId': typeof ApiApiKeysWorkspaceIdProjectIdIndexRoute
  '/projects/$projectId/screenshots': typeof AuthOrgProjectsProjectIdScreenshotsIndexRoute
  '/projects/$projectId/namespaces/$namespaceId/editor': typeof AuthOrgProjectsProjectIdNamespacesNamespaceIdEditorRoute
  '/projects/$projectId/screenshots/$screenshotId': typeof AuthOrgProjectsProjectIdScreenshotsScreenshotIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/new': typeof AuthNewRoute
  '/select-org': typeof AuthSelectOrgRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard/billing': typeof AuthOrgDashboardBillingRoute
  '/dashboard/logs': typeof AuthOrgDashboardLogsRoute
  '/dashboard': typeof AuthOrgDashboardIndexRoute
  '/projects/$projectId/api-keys': typeof AuthOrgProjectsProjectIdApiKeysRoute
  '/projects/$projectId/builds': typeof AuthOrgProjectsProjectIdBuildsRoute
  '/projects/$projectId/glossary': typeof AuthOrgProjectsProjectIdGlossaryRoute
  '/projects/$projectId/languages': typeof AuthOrgProjectsProjectIdLanguagesRoute
  '/projects/$projectId/releases': typeof AuthOrgProjectsProjectIdReleasesRoute
  '/api/api-keys/$workspaceId/$projectId/$keyId': typeof ApiApiKeysWorkspaceIdProjectIdKeyIdRoute
  '/projects/$projectId': typeof AuthOrgProjectsProjectIdIndexRoute
  '/api/api-keys/$workspaceId/$projectId': typeof ApiApiKeysWorkspaceIdProjectIdIndexRoute
  '/projects/$projectId/screenshots': typeof AuthOrgProjectsProjectIdScreenshotsIndexRoute
  '/projects/$projectId/namespaces/$namespaceId/editor': typeof AuthOrgProjectsProjectIdNamespacesNamespaceIdEditorRoute
  '/projects/$projectId/screenshots/$screenshotId': typeof AuthOrgProjectsProjectIdScreenshotsScreenshotIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/_auth/_org': typeof AuthOrgRouteWithChildren
  '/_auth/new': typeof AuthNewRoute
  '/_auth/select-org': typeof AuthSelectOrgRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_auth/_org/dashboard/billing': typeof AuthOrgDashboardBillingRoute
  '/_auth/_org/dashboard/logs': typeof AuthOrgDashboardLogsRoute
  '/_auth/_org/dashboard/': typeof AuthOrgDashboardIndexRoute
  '/_auth/_org/projects/$projectId/api-keys': typeof AuthOrgProjectsProjectIdApiKeysRoute
  '/_auth/_org/projects/$projectId/builds': typeof AuthOrgProjectsProjectIdBuildsRoute
  '/_auth/_org/projects/$projectId/glossary': typeof AuthOrgProjectsProjectIdGlossaryRoute
  '/_auth/_org/projects/$projectId/languages': typeof AuthOrgProjectsProjectIdLanguagesRoute
  '/_auth/_org/projects/$projectId/releases': typeof AuthOrgProjectsProjectIdReleasesRoute
  '/api/api-keys/$workspaceId/$projectId/$keyId': typeof ApiApiKeysWorkspaceIdProjectIdKeyIdRoute
  '/_auth/_org/projects/$projectId/': typeof AuthOrgProjectsProjectIdIndexRoute
  '/api/api-keys/$workspaceId/$projectId/': typeof ApiApiKeysWorkspaceIdProjectIdIndexRoute
  '/_auth/_org/projects/$projectId/screenshots/': typeof AuthOrgProjectsProjectIdScreenshotsIndexRoute
  '/_auth/_org/projects/$projectId/namespaces/$namespaceId/editor': typeof AuthOrgProjectsProjectIdNamespacesNamespaceIdEditorRoute
  '/_auth/_org/projects/$projectId/screenshots/$screenshotId/': typeof AuthOrgProjectsProjectIdScreenshotsScreenshotIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/new'
    | '/select-org'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard/billing'
    | '/dashboard/logs'
    | '/dashboard'
    | '/projects/$projectId/api-keys'
    | '/projects/$projectId/builds'
    | '/projects/$projectId/glossary'
    | '/projects/$projectId/languages'
    | '/projects/$projectId/releases'
    | '/api/api-keys/$workspaceId/$projectId/$keyId'
    | '/projects/$projectId'
    | '/api/api-keys/$workspaceId/$projectId'
    | '/projects/$projectId/screenshots'
    | '/projects/$projectId/namespaces/$namespaceId/editor'
    | '/projects/$projectId/screenshots/$screenshotId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/new'
    | '/select-org'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard/billing'
    | '/dashboard/logs'
    | '/dashboard'
    | '/projects/$projectId/api-keys'
    | '/projects/$projectId/builds'
    | '/projects/$projectId/glossary'
    | '/projects/$projectId/languages'
    | '/projects/$projectId/releases'
    | '/api/api-keys/$workspaceId/$projectId/$keyId'
    | '/projects/$projectId'
    | '/api/api-keys/$workspaceId/$projectId'
    | '/projects/$projectId/screenshots'
    | '/projects/$projectId/namespaces/$namespaceId/editor'
    | '/projects/$projectId/screenshots/$screenshotId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/about'
    | '/_auth/_org'
    | '/_auth/new'
    | '/_auth/select-org'
    | '/legal/privacy-policy'
    | '/legal/terms-of-service'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_auth/_org/dashboard/billing'
    | '/_auth/_org/dashboard/logs'
    | '/_auth/_org/dashboard/'
    | '/_auth/_org/projects/$projectId/api-keys'
    | '/_auth/_org/projects/$projectId/builds'
    | '/_auth/_org/projects/$projectId/glossary'
    | '/_auth/_org/projects/$projectId/languages'
    | '/_auth/_org/projects/$projectId/releases'
    | '/api/api-keys/$workspaceId/$projectId/$keyId'
    | '/_auth/_org/projects/$projectId/'
    | '/api/api-keys/$workspaceId/$projectId/'
    | '/_auth/_org/projects/$projectId/screenshots/'
    | '/_auth/_org/projects/$projectId/namespaces/$namespaceId/editor'
    | '/_auth/_org/projects/$projectId/screenshots/$screenshotId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
  LegalTermsOfServiceRoute: typeof LegalTermsOfServiceRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  ApiApiKeysWorkspaceIdProjectIdKeyIdRoute: typeof ApiApiKeysWorkspaceIdProjectIdKeyIdRoute
  ApiApiKeysWorkspaceIdProjectIdIndexRoute: typeof ApiApiKeysWorkspaceIdProjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms-of-service': {
      id: '/legal/terms-of-service'
      path: '/legal/terms-of-service'
      fullPath: '/legal/terms-of-service'
      preLoaderRoute: typeof LegalTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy-policy': {
      id: '/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/select-org': {
      id: '/_auth/select-org'
      path: '/select-org'
      fullPath: '/select-org'
      preLoaderRoute: typeof AuthSelectOrgRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/new': {
      id: '/_auth/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_org': {
      id: '/_auth/_org'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthOrgRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_org/dashboard/': {
      id: '/_auth/_org/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthOrgDashboardIndexRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/_org/dashboard/logs': {
      id: '/_auth/_org/dashboard/logs'
      path: '/dashboard/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof AuthOrgDashboardLogsRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/_org/dashboard/billing': {
      id: '/_auth/_org/dashboard/billing'
      path: '/dashboard/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof AuthOrgDashboardBillingRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/api/api-keys/$workspaceId/$projectId/': {
      id: '/api/api-keys/$workspaceId/$projectId/'
      path: '/api/api-keys/$workspaceId/$projectId'
      fullPath: '/api/api-keys/$workspaceId/$projectId'
      preLoaderRoute: typeof ApiApiKeysWorkspaceIdProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_org/projects/$projectId/': {
      id: '/_auth/_org/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthOrgProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/api/api-keys/$workspaceId/$projectId/$keyId': {
      id: '/api/api-keys/$workspaceId/$projectId/$keyId'
      path: '/api/api-keys/$workspaceId/$projectId/$keyId'
      fullPath: '/api/api-keys/$workspaceId/$projectId/$keyId'
      preLoaderRoute: typeof ApiApiKeysWorkspaceIdProjectIdKeyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_org/projects/$projectId/releases': {
      id: '/_auth/_org/projects/$projectId/releases'
      path: '/projects/$projectId/releases'
      fullPath: '/projects/$projectId/releases'
      preLoaderRoute: typeof AuthOrgProjectsProjectIdReleasesRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/_org/projects/$projectId/languages': {
      id: '/_auth/_org/projects/$projectId/languages'
      path: '/projects/$projectId/languages'
      fullPath: '/projects/$projectId/languages'
      preLoaderRoute: typeof AuthOrgProjectsProjectIdLanguagesRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/_org/projects/$projectId/glossary': {
      id: '/_auth/_org/projects/$projectId/glossary'
      path: '/projects/$projectId/glossary'
      fullPath: '/projects/$projectId/glossary'
      preLoaderRoute: typeof AuthOrgProjectsProjectIdGlossaryRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/_org/projects/$projectId/builds': {
      id: '/_auth/_org/projects/$projectId/builds'
      path: '/projects/$projectId/builds'
      fullPath: '/projects/$projectId/builds'
      preLoaderRoute: typeof AuthOrgProjectsProjectIdBuildsRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/_org/projects/$projectId/api-keys': {
      id: '/_auth/_org/projects/$projectId/api-keys'
      path: '/projects/$projectId/api-keys'
      fullPath: '/projects/$projectId/api-keys'
      preLoaderRoute: typeof AuthOrgProjectsProjectIdApiKeysRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/_org/projects/$projectId/screenshots/': {
      id: '/_auth/_org/projects/$projectId/screenshots/'
      path: '/projects/$projectId/screenshots'
      fullPath: '/projects/$projectId/screenshots'
      preLoaderRoute: typeof AuthOrgProjectsProjectIdScreenshotsIndexRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/_org/projects/$projectId/screenshots/$screenshotId/': {
      id: '/_auth/_org/projects/$projectId/screenshots/$screenshotId/'
      path: '/projects/$projectId/screenshots/$screenshotId'
      fullPath: '/projects/$projectId/screenshots/$screenshotId'
      preLoaderRoute: typeof AuthOrgProjectsProjectIdScreenshotsScreenshotIdIndexRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/_org/projects/$projectId/namespaces/$namespaceId/editor': {
      id: '/_auth/_org/projects/$projectId/namespaces/$namespaceId/editor'
      path: '/projects/$projectId/namespaces/$namespaceId/editor'
      fullPath: '/projects/$projectId/namespaces/$namespaceId/editor'
      preLoaderRoute: typeof AuthOrgProjectsProjectIdNamespacesNamespaceIdEditorRouteImport
      parentRoute: typeof AuthOrgRoute
    }
  }
}

interface AuthOrgRouteChildren {
  AuthOrgDashboardBillingRoute: typeof AuthOrgDashboardBillingRoute
  AuthOrgDashboardLogsRoute: typeof AuthOrgDashboardLogsRoute
  AuthOrgDashboardIndexRoute: typeof AuthOrgDashboardIndexRoute
  AuthOrgProjectsProjectIdApiKeysRoute: typeof AuthOrgProjectsProjectIdApiKeysRoute
  AuthOrgProjectsProjectIdBuildsRoute: typeof AuthOrgProjectsProjectIdBuildsRoute
  AuthOrgProjectsProjectIdGlossaryRoute: typeof AuthOrgProjectsProjectIdGlossaryRoute
  AuthOrgProjectsProjectIdLanguagesRoute: typeof AuthOrgProjectsProjectIdLanguagesRoute
  AuthOrgProjectsProjectIdReleasesRoute: typeof AuthOrgProjectsProjectIdReleasesRoute
  AuthOrgProjectsProjectIdIndexRoute: typeof AuthOrgProjectsProjectIdIndexRoute
  AuthOrgProjectsProjectIdScreenshotsIndexRoute: typeof AuthOrgProjectsProjectIdScreenshotsIndexRoute
  AuthOrgProjectsProjectIdNamespacesNamespaceIdEditorRoute: typeof AuthOrgProjectsProjectIdNamespacesNamespaceIdEditorRoute
  AuthOrgProjectsProjectIdScreenshotsScreenshotIdIndexRoute: typeof AuthOrgProjectsProjectIdScreenshotsScreenshotIdIndexRoute
}

const AuthOrgRouteChildren: AuthOrgRouteChildren = {
  AuthOrgDashboardBillingRoute: AuthOrgDashboardBillingRoute,
  AuthOrgDashboardLogsRoute: AuthOrgDashboardLogsRoute,
  AuthOrgDashboardIndexRoute: AuthOrgDashboardIndexRoute,
  AuthOrgProjectsProjectIdApiKeysRoute: AuthOrgProjectsProjectIdApiKeysRoute,
  AuthOrgProjectsProjectIdBuildsRoute: AuthOrgProjectsProjectIdBuildsRoute,
  AuthOrgProjectsProjectIdGlossaryRoute: AuthOrgProjectsProjectIdGlossaryRoute,
  AuthOrgProjectsProjectIdLanguagesRoute:
    AuthOrgProjectsProjectIdLanguagesRoute,
  AuthOrgProjectsProjectIdReleasesRoute: AuthOrgProjectsProjectIdReleasesRoute,
  AuthOrgProjectsProjectIdIndexRoute: AuthOrgProjectsProjectIdIndexRoute,
  AuthOrgProjectsProjectIdScreenshotsIndexRoute:
    AuthOrgProjectsProjectIdScreenshotsIndexRoute,
  AuthOrgProjectsProjectIdNamespacesNamespaceIdEditorRoute:
    AuthOrgProjectsProjectIdNamespacesNamespaceIdEditorRoute,
  AuthOrgProjectsProjectIdScreenshotsScreenshotIdIndexRoute:
    AuthOrgProjectsProjectIdScreenshotsScreenshotIdIndexRoute,
}

const AuthOrgRouteWithChildren =
  AuthOrgRoute._addFileChildren(AuthOrgRouteChildren)

interface AuthRouteChildren {
  AuthOrgRoute: typeof AuthOrgRouteWithChildren
  AuthNewRoute: typeof AuthNewRoute
  AuthSelectOrgRoute: typeof AuthSelectOrgRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthOrgRoute: AuthOrgRouteWithChildren,
  AuthNewRoute: AuthNewRoute,
  AuthSelectOrgRoute: AuthSelectOrgRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
  LegalTermsOfServiceRoute: LegalTermsOfServiceRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  ApiApiKeysWorkspaceIdProjectIdKeyIdRoute:
    ApiApiKeysWorkspaceIdProjectIdKeyIdRoute,
  ApiApiKeysWorkspaceIdProjectIdIndexRoute:
    ApiApiKeysWorkspaceIdProjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
