/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AuthNewRouteImport } from './routes/_auth/new'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth/dashboard/index'
import { Route as AuthDashboardLogsRouteImport } from './routes/_auth/dashboard/logs'
import { Route as AuthDashboardBillingRouteImport } from './routes/_auth/dashboard/billing'
import { Route as AuthProjectsProjectIdIndexRouteImport } from './routes/_auth/projects/$projectId/index'
import { Route as AuthProjectsProjectIdApiKeysRouteImport } from './routes/_auth/projects/$projectId/api-keys'
import { Route as ApiApiKeysWorkspaceIdProjectIdIndexRouteImport } from './routes/api/api-keys/$workspaceId.$projectId/index'
import { Route as ApiApiKeysWorkspaceIdProjectIdKeyIdRouteImport } from './routes/api/api-keys/$workspaceId.$projectId/$keyId'
import { Route as AuthProjectsProjectIdNamespacesNamespaceIdVersionsVersionIdEditorRouteImport } from './routes/_auth/projects/$projectId/namespaces/$namespaceId/versions/$versionId/editor'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthNewRoute = AuthNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardLogsRoute = AuthDashboardLogsRouteImport.update({
  id: '/dashboard/logs',
  path: '/dashboard/logs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardBillingRoute = AuthDashboardBillingRouteImport.update({
  id: '/dashboard/billing',
  path: '/dashboard/billing',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsProjectIdIndexRoute =
  AuthProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthProjectsProjectIdApiKeysRoute =
  AuthProjectsProjectIdApiKeysRouteImport.update({
    id: '/projects/$projectId/api-keys',
    path: '/projects/$projectId/api-keys',
    getParentRoute: () => AuthRoute,
  } as any)
const ApiApiKeysWorkspaceIdProjectIdIndexRoute =
  ApiApiKeysWorkspaceIdProjectIdIndexRouteImport.update({
    id: '/api/api-keys/$workspaceId/$projectId/',
    path: '/api/api-keys/$workspaceId/$projectId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiApiKeysWorkspaceIdProjectIdKeyIdRoute =
  ApiApiKeysWorkspaceIdProjectIdKeyIdRouteImport.update({
    id: '/api/api-keys/$workspaceId/$projectId/$keyId',
    path: '/api/api-keys/$workspaceId/$projectId/$keyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthProjectsProjectIdNamespacesNamespaceIdVersionsVersionIdEditorRoute =
  AuthProjectsProjectIdNamespacesNamespaceIdVersionsVersionIdEditorRouteImport.update(
    {
      id: '/projects/$projectId/namespaces/$namespaceId/versions/$versionId/editor',
      path: '/projects/$projectId/namespaces/$namespaceId/versions/$versionId/editor',
      getParentRoute: () => AuthRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof AuthNewRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard/billing': typeof AuthDashboardBillingRoute
  '/dashboard/logs': typeof AuthDashboardLogsRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/projects/$projectId/api-keys': typeof AuthProjectsProjectIdApiKeysRoute
  '/projects/$projectId': typeof AuthProjectsProjectIdIndexRoute
  '/api/api-keys/$workspaceId/$projectId/$keyId': typeof ApiApiKeysWorkspaceIdProjectIdKeyIdRoute
  '/api/api-keys/$workspaceId/$projectId': typeof ApiApiKeysWorkspaceIdProjectIdIndexRoute
  '/projects/$projectId/namespaces/$namespaceId/versions/$versionId/editor': typeof AuthProjectsProjectIdNamespacesNamespaceIdVersionsVersionIdEditorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof AuthNewRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard/billing': typeof AuthDashboardBillingRoute
  '/dashboard/logs': typeof AuthDashboardLogsRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/projects/$projectId/api-keys': typeof AuthProjectsProjectIdApiKeysRoute
  '/projects/$projectId': typeof AuthProjectsProjectIdIndexRoute
  '/api/api-keys/$workspaceId/$projectId/$keyId': typeof ApiApiKeysWorkspaceIdProjectIdKeyIdRoute
  '/api/api-keys/$workspaceId/$projectId': typeof ApiApiKeysWorkspaceIdProjectIdIndexRoute
  '/projects/$projectId/namespaces/$namespaceId/versions/$versionId/editor': typeof AuthProjectsProjectIdNamespacesNamespaceIdVersionsVersionIdEditorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/new': typeof AuthNewRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_auth/dashboard/billing': typeof AuthDashboardBillingRoute
  '/_auth/dashboard/logs': typeof AuthDashboardLogsRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/projects/$projectId/api-keys': typeof AuthProjectsProjectIdApiKeysRoute
  '/_auth/projects/$projectId/': typeof AuthProjectsProjectIdIndexRoute
  '/api/api-keys/$workspaceId/$projectId/$keyId': typeof ApiApiKeysWorkspaceIdProjectIdKeyIdRoute
  '/api/api-keys/$workspaceId/$projectId/': typeof ApiApiKeysWorkspaceIdProjectIdIndexRoute
  '/_auth/projects/$projectId/namespaces/$namespaceId/versions/$versionId/editor': typeof AuthProjectsProjectIdNamespacesNamespaceIdVersionsVersionIdEditorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard/billing'
    | '/dashboard/logs'
    | '/dashboard'
    | '/projects/$projectId/api-keys'
    | '/projects/$projectId'
    | '/api/api-keys/$workspaceId/$projectId/$keyId'
    | '/api/api-keys/$workspaceId/$projectId'
    | '/projects/$projectId/namespaces/$namespaceId/versions/$versionId/editor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/dashboard/billing'
    | '/dashboard/logs'
    | '/dashboard'
    | '/projects/$projectId/api-keys'
    | '/projects/$projectId'
    | '/api/api-keys/$workspaceId/$projectId/$keyId'
    | '/api/api-keys/$workspaceId/$projectId'
    | '/projects/$projectId/namespaces/$namespaceId/versions/$versionId/editor'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/new'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_auth/dashboard/billing'
    | '/_auth/dashboard/logs'
    | '/_auth/dashboard/'
    | '/_auth/projects/$projectId/api-keys'
    | '/_auth/projects/$projectId/'
    | '/api/api-keys/$workspaceId/$projectId/$keyId'
    | '/api/api-keys/$workspaceId/$projectId/'
    | '/_auth/projects/$projectId/namespaces/$namespaceId/versions/$versionId/editor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  ApiApiKeysWorkspaceIdProjectIdKeyIdRoute: typeof ApiApiKeysWorkspaceIdProjectIdKeyIdRoute
  ApiApiKeysWorkspaceIdProjectIdIndexRoute: typeof ApiApiKeysWorkspaceIdProjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/new': {
      id: '/_auth/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/logs': {
      id: '/_auth/dashboard/logs'
      path: '/dashboard/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof AuthDashboardLogsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/billing': {
      id: '/_auth/dashboard/billing'
      path: '/dashboard/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof AuthDashboardBillingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/$projectId/': {
      id: '/_auth/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/$projectId/api-keys': {
      id: '/_auth/projects/$projectId/api-keys'
      path: '/projects/$projectId/api-keys'
      fullPath: '/projects/$projectId/api-keys'
      preLoaderRoute: typeof AuthProjectsProjectIdApiKeysRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/api-keys/$workspaceId/$projectId/': {
      id: '/api/api-keys/$workspaceId/$projectId/'
      path: '/api/api-keys/$workspaceId/$projectId'
      fullPath: '/api/api-keys/$workspaceId/$projectId'
      preLoaderRoute: typeof ApiApiKeysWorkspaceIdProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api-keys/$workspaceId/$projectId/$keyId': {
      id: '/api/api-keys/$workspaceId/$projectId/$keyId'
      path: '/api/api-keys/$workspaceId/$projectId/$keyId'
      fullPath: '/api/api-keys/$workspaceId/$projectId/$keyId'
      preLoaderRoute: typeof ApiApiKeysWorkspaceIdProjectIdKeyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/projects/$projectId/namespaces/$namespaceId/versions/$versionId/editor': {
      id: '/_auth/projects/$projectId/namespaces/$namespaceId/versions/$versionId/editor'
      path: '/projects/$projectId/namespaces/$namespaceId/versions/$versionId/editor'
      fullPath: '/projects/$projectId/namespaces/$namespaceId/versions/$versionId/editor'
      preLoaderRoute: typeof AuthProjectsProjectIdNamespacesNamespaceIdVersionsVersionIdEditorRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthNewRoute: typeof AuthNewRoute
  AuthDashboardBillingRoute: typeof AuthDashboardBillingRoute
  AuthDashboardLogsRoute: typeof AuthDashboardLogsRoute
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
  AuthProjectsProjectIdApiKeysRoute: typeof AuthProjectsProjectIdApiKeysRoute
  AuthProjectsProjectIdIndexRoute: typeof AuthProjectsProjectIdIndexRoute
  AuthProjectsProjectIdNamespacesNamespaceIdVersionsVersionIdEditorRoute: typeof AuthProjectsProjectIdNamespacesNamespaceIdVersionsVersionIdEditorRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthNewRoute: AuthNewRoute,
  AuthDashboardBillingRoute: AuthDashboardBillingRoute,
  AuthDashboardLogsRoute: AuthDashboardLogsRoute,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
  AuthProjectsProjectIdApiKeysRoute: AuthProjectsProjectIdApiKeysRoute,
  AuthProjectsProjectIdIndexRoute: AuthProjectsProjectIdIndexRoute,
  AuthProjectsProjectIdNamespacesNamespaceIdVersionsVersionIdEditorRoute:
    AuthProjectsProjectIdNamespacesNamespaceIdVersionsVersionIdEditorRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  ApiApiKeysWorkspaceIdProjectIdKeyIdRoute:
    ApiApiKeysWorkspaceIdProjectIdKeyIdRoute,
  ApiApiKeysWorkspaceIdProjectIdIndexRoute:
    ApiApiKeysWorkspaceIdProjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
